### ISSUE TITLE
Game doesn't save.

### ISSUE THREAD

**Issue by mcmcelro** [Symb1/progress_knight_2#4]
Sometime in the last couple of days, a change was made that broke the automatic save feature. Unless you manually go into the console and type `saveGameData()`, the game never saves. I found this out by refreshing the tab and losing 3 days of progress.

The only time that saving occurs is 3 seconds after the page loads:

`setInterval(saveGameData, 3000)`

This is never called again, and placing a breakpoint in the saveGameData function reveals that it never runs more than once.

**Comment by Symb1** [comment]
setInterval(saveGameData, 3000) is on the line 1644
